name: anytime
description: Anytime Podcast Player
publish_to: none
version: 1.2.1+74-breez

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=3.7.5"

dependencies:
  auto_size_text: ^3.0.0
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  extended_image: ^7.0.2
  file_picker: ^5.2.5
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.10.2
  flutter_html: ^3.0.0-alpha.6
  flutter_launcher_icons: ^0.12.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.2
  html: ^0.15.1
  intl: ^0.18.0
  just_audio: ^0.9.31
  logging: ^1.1.1
  meta: ^1.9.0
  mp3_info: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.0.13
  path_provider_platform_interface: ^2.0.6
  percent_indicator: 4.2.2
  permission_handler: ^10.2.0
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 8190101aa49edf0f501cf3688f32a3a87df137c5
  provider: ^6.0.5
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.5
  sembast: ^3.4.0+6
  share_plus: ^6.3.1
  shared_preferences: ^2.0.18
  uni_links: ^0.5.1
  url_launcher: ^6.1.10
  xml: ^6.2.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^5.3.2
  pedantic: ^1.11.1
  flutter_lints: ^2.0.1
  intl_generator: ^0.4.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0
  meta: ^1.9.0
  path: ^1.8.3

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png
    - assets/icons/

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
