name: anytime
description: Anytime Podcast Player
publish_to: none
version: 2.0.0-breez

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  auto_size_text: ^3.0.0
  audio_service: ^0.18.9
  audio_session: ^0.1.14
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.0
  extended_image: ^8.0.1
  file_picker: ^5.3.0
  flutter_dialogs: ^3.0.0
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
  flutter_html: ^3.0.0-beta.1
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.5
  html: ^0.15.3
  intl: ^0.18.1
  just_audio: ^0.9.33
  logging: ^1.1.1
  meta: ^1.9.1
  mp3_info: ^0.2.1
  path: ^1.8.3
  path_provider: ^2.0.15
  path_provider_platform_interface: ^2.0.6
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 8190101aa49edf0f501cf3688f32a3a87df137c5
  provider: ^6.0.5
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  sembast: ^3.4.4
  share_plus: ^7.0.0
  shared_preferences: ^2.1.1
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  xml: ^6.3.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.2

dev_dependencies:
  mockito: ^5.4.0
  pedantic: ^1.11.1
  flutter_lints: ^2.0.1
  intl_generator: ^0.4.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.17.2

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png
    - assets/icons/

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
